autoInstallPeers: false
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade
packages: []

catalogs:
  build:
    '@nuxt/content': ^3.15.0
    '@nuxt/devtools': ^3.2.4
    '@nuxt/eslint': ^1.15.2
    '@nuxt/image': 2.0.0
    '@nuxt/kit': ^4.4.2
    '@nuxtjs/color-mode': ^4.0.0
    '@pinia/nuxt': ^0.11.3
    '@unocss/eslint-config': ^66.6.7
    '@unocss/nuxt': ^66.6.7
    '@vueuse/nuxt': ^14.2.1
    chokidar: ^5.0.0
    nuxt: ^4.4.2
    semver: ^7.7.4
    unocss: ^66.6.7
    unplugin: ^3.0.0
    vite: ^8.0.0
    wrangler: ^4.118.0
  dev:
    '@antfu/eslint-config': ^7.7.3
    '@antfu/ni': ^30.2.0
    '@types/node': ^25.5.0
    better-sqlite3: ^12.11.1
    eslint: ^10.0.3
    eslint-plugin-format: ^2.0.1
    taze: ^19.14.1
    typescript: ^5.9.3
    vitest: ^4.1.10
    vue-tsc: ^3.2.6
    zod: ^4.4.3
  frontend:
    '@vueuse/core': ^14.2.1
    gsap: ^3.15.0
    pinia: ^3.0.4
    three: ^0.185.1
    vue: ^3.5.30
  icons:
    '@iconify/json': ^2.2.495
  types:
    '@types/three': ^0.185.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
